//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PAGO_TARJETA
    {
        public int ID { get; set; }

        [DisplayName("Número de Tarjeta")]
        public Nullable<int> ID_TARJETA { get; set; }

        [DisplayName("Número de Cuenta")]
        public Nullable<int> Cuenta_id { get; set; }
        public string Cedula { get; set; }

        [DisplayName("Balance disponible")]
        public Nullable<int> Balance { get; set; }

        [DisplayName("Balance")]
        public Nullable<int> Balance_Limite { get; set; }

        [DisplayName("Total de Pago")]
        public Nullable<int> Total_Pago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
