//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PAGOS
    {
        public int ID { get; set; }

        [DisplayName("Cuenta a debitar")]
        public Nullable<int> Cuenta_pago { get; set; }

        [DisplayName("Cuenta a transferir")]
        public Nullable<int> Cuenta_deposito { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual CUENTAS CUENTAS { get; set; }
        public virtual CUENTAS CUENTAS1 { get; set; }
    }
}
