//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PAGO_PRESTAMO
    {
        public int ID { get; set; }

        [DisplayName("Número")]
        public Nullable<int> ID_PRESTAMO { get; set; }
        public string Cedula { get; set; }
        public Nullable<int> Cuenta_id { get; set; }
        public Nullable<int> Cuota_Mensual { get; set; }
        public Nullable<int> Cantidad_meses { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
