//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PRESTAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTAMO()
        {
            this.PAGO_PRESTAMO = new HashSet<PAGO_PRESTAMO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Monto { get; set; }
        public string Cedula { get; set; }

        [DisplayName("Número de Cuenta")]

        public Nullable<int> Cuenta_id { get; set; }

        [DisplayName("Cuota")]
        public Nullable<int> Cuota_Mensual { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Cantidad_Meses { get; set; }
    
        public virtual CUENTAS CUENTAS { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO_PRESTAMO> PAGO_PRESTAMO { get; set; }
    }
}
