//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Reporte_Prestamos
    {
        public int ID { get; set; }

        [DisplayName("Monto")]
        public Nullable<int> MONTO { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }

        [DisplayName("Número de Cuenta")]
        public Nullable<int> Cuenta_id { get; set; }
        public Nullable<int> Cuota { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }

        [DisplayName("Canidad de Meses")]
        public Nullable<int> Cantidad_Meses { get; set; }
    }
}
