//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ReportesCuentas
    {
        public int Cuenta { get; set; }


        public string Nombre_Cliente { get; set; }
        public string Apellido { get; set; }

        [DisplayName("Balance disponible")]
        public Nullable<int> Balance { get; set; }

        [DisplayName("Balance")]
        public Nullable<int> Monto_Limite { get; set; }
        public string Estado { get; set; }
    }
}
