//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TARJETAS
    {
        public int Numero { get; set; }
        public Nullable<int> Cuenta_id { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> Fecha_de_Vencimiento { get; set; }

        [DisplayName("Balance Disponible")]
        public Nullable<int> BALANCE { get; set; }

        [DisplayName("Balance")]
        public Nullable<int> BALANCE_LIMITE { get; set; }
        public string Estatus { get; set; }
    
        public virtual CUENTAS CUENTAS { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
