//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TRANSACCION
    {
        public int ID { get; set; }

        [DisplayName("Cuenta a debitar")]
        public int ID_CUENTA_DEPOSITO { get; set; }

        [DisplayName("Cuenta a transferir")]
        public Nullable<int> ID_CUENTA_ENVIO { get; set; }

        [DisplayName("Monto")]
        public int DINERO { get; set; }

        [DisplayName("Fecha")]
        public Nullable<System.DateTime> FECHA { get; set; }

        [DisplayName("Tipo de Transacción")]
        public string Tipo_Transaccion { get; set; }
    }
}
