//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TRANSACCION_TARJETA
    {
        public int ID { get; set; }

        [DisplayName("Número de Tarjeta")]
        public int Numero_Tarjeta { get; set; }

        [DisplayName("Cuenta a depositar")]

        public int ID_CUENTA_ENVIO { get; set; }

        [DisplayName("Monto")]
        public int DINERO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
